<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU_2" Id="{5dd7250e-f1a5-4f25-b632-9e9acc7716d7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>